### ISSUE TITLE
Collapse main branch with dev/master

### ISSUE THREAD

**Issue by cthoyt** [indralab/indra_network_search#18]
Right now if someone looks at this repo, it seems like it hasn't been touched in 8 months. I'd suggest merging dev/master directly into main, then just working there.

**Comment by cthoyt** [comment]
Maybe to make this a bit easier, you can make a tag on the current state on main, which I'll guess corresponds to the old version of the service. Then if there's a tag, it's easy to get back to the old version, and then there's no need to have a monolithic new branch/PR

**Comment by kkaris** [comment]
Agreed. I'll tag the old-service and make my draft PR #11 an actual PR and then we can merge it once I'm done.

**Comment by kkaris** [comment]
Resolved in #11.
