### ISSUE TITLE
Pkl file not available

### ISSUE THREAD

**Issue by Crispae** [indralab/indra_network_search#29]
I was trying to build a docker container, but getting error as there is no "indranet_dir_graph.pkl" file. Can you please provide this file?
Thanks

**Comment by bgyori** [comment]
Hi @Crispae, thanks for your interest! Currently, the way the service is set up, is that we provide the public website (https://network.indra.bio/#/) as well as a REST API for using the network search, while allowing users to set up local searches with their own graphs. We are currently not distributing the indranet_dir_graph.pkl as a public resource, however, that might change in the future.

**Comment by Crispae** [comment]
Thanks for your respone,Btw this tool will be really helpful for biochemical community.
